### PR TITLE
Checkout into new subdir

### PR DESCRIPTION
**Pull request by dcermak**

### CODE REVIEW

**Comment by dcermak** [comment]
@KeithMnemonic Could you install the vsix from the github actions (https://github.com/SUSE/open-build-service-connector/suites/2188329895/artifacts/45096866, note that it's a zip and needs to be extracted first) and see if the new behavior is to your liking?

**Comment by KeithMnemonic** [comment]
> @KeithMnemonic Could you install the vsix from the github actions (https://github.com/SUSE/open-build-service-connector/suites/2188329895/artifacts/45096866, note that it's a zip and needs to be extracted first) and see if the new behavior is to your liking?

With the latest version 0.0.6 I am getting 

Command 'Add an existing account from the Open Build Service to the extension' resulted in an error (command 'vscodeObs.obsAccount.newAccountWizard' not found)

Did I need to remove the old version prior or such?

**Comment by KeithMnemonic** [comment]
> > @KeithMnemonic Could you install the vsix from the github actions (https://github.com/SUSE/open-build-service-connector/suites/2188329895/artifacts/45096866, note that it's a zip and needs to be extracted first) and see if the new behavior is to your liking?
> 
> With the latest version 0.0.6 I am getting
> 
> Command 'Add an existing account from the Open Build Service to the extension' resulted in an error (command 'vscodeObs.obsAccount.newAccountWizard' not found)
> 
> Did I need to remove the old version prior or such?

even removing 0.0.5 and also reinstalling 0.0.6 shows the error. The code does seem to have the module though


 kberger@keith-wks  ~/.vscode-server/extensions  grep -R vscodeObs.obsAccount.newAccountWizard | more
suse.open-build-service-connector-0.0.6/package.json:                           "command": "vscodeObs.obsAccount.newAcco
untWizard"
suse.open-build-service-connector-0.0.6/package.json:                           "contents": "You don't appear to have an
y Accounts configured.\n[Add a new Account](command:vscodeObs.obsAccount.newAccountWizard)\n[Import accounts from osc](c
ommand:vscodeObs.obsAccount.importAccountsFromOsrc)",
suse.open-build-service-connector-0.0.6/dist/extension.js:((

**Comment by dcermak** [comment]
> > > @KeithMnemonic Could you install the vsix from the github actions (https://github.com/SUSE/open-build-service-connector/suites/2188329895/artifacts/45096866, note that it's a zip and needs to be extracted first) and see if the new behavior is to your liking?
> > 
> > 
> > With the latest version 0.0.6 I am getting
> > Command 'Add an existing account from the Open Build Service to the extension' resulted in an error (command 'vscodeObs.obsAccount.newAccountWizard' not found)
> > Did I need to remove the old version prior or such?
> 
> even removing 0.0.5 and also reinstalling 0.0.6 shows the error. The code does seem to have the module though
> 
> kberger@keith-wks  ~/.vscode-server/extensions  grep -R vscodeObs.obsAccount.newAccountWizard | more
> suse.open-build-service-connector-0.0.6/package.json: "command": "vscodeObs.obsAccount.newAcco
> untWizard"
> suse.open-build-service-connector-0.0.6/package.json: "contents": "You don't appear to have an
> y Accounts configured.\nAdd a new Account\n[Import accounts from osc](c
> ommand:vscodeObs.obsAccount.importAccountsFromOsrc)",
> suse.open-build-service-connector-0.0.6/dist/extension.js:((

That is extremely weird and should definitely not be happening (also, I cannot reproduce that issue locally). Could you execute the command "Open Error Reporting Page" and paste the log that you get into a new issue?

**Pull request merged**
